### ISSUE TITLE
Use gopkg.in for the versioning

### ISSUE THREAD

**Issue by jseun** [go-prompt/prompt#2]
Hey there, I would use that package for my application but it would be nice to refer to it as `import "gopkg.in/prompt.v1"` so that if you change the API, you would make it in a v2 version.

Gopkg.in is dead simple.  I'd like to see your package in `github.com/go-prompt/prompt` with a v1 branch.  There is no go-prompt organization (or user) yet.

**Comment by viliamjr** [comment]
Hi! API versioning would be nice. I'll check `gopkg.in` this weekend.

**Comment by viliamjr** [comment]
Done. Please test.

**Comment by jseun** [comment]
Should work as expected.  Thank you!  I have tried `go get gopkg.in/prompt.v1` and it installed just fine.
